cache_control_attachment_max_age: 10800
cache_control_attachment_staleerror: 10800
cache_control_attachment_stalereval: 10800
cache_control_attachment_s_maxage: 5300
cache_control_authors_max_age: 1800
cache_control_authors_paged: 10
cache_control_authors_staleerror: 1800
cache_control_authors_stalereval: 1800
cache_control_authors_s_maxage: 900
cache_control_categories_max_age: 900
cache_control_categories_paged: 8
cache_control_categories_staleerror: 1800
cache_control_categories_stalereval: 1800
cache_control_categories_s_maxage: 450
cache_control_dates_max_age: 10800
cache_control_dates_staleerror: 10800
cache_control_dates_stalereval: 10800
cache_control_dates_s_maxage: 5400
cache_control_feeds_max_age: 5400
cache_control_feeds_staleerror: 5400
cache_control_feeds_stalereval: 5400
cache_control_feeds_s_maxage: 2700
cache_control_front_page_max_age: 3600
cache_control_front_page_staleerror: 7200
cache_control_front_page_stalereval: 7200
cache_control_front_page_s_maxage: 1800
cache_control_home_max_age: 3600
cache_control_home_paged: 5
cache_control_home_staleerror: 7200
cache_control_home_stalereval: 7200
cache_control_home_s_maxage: 1800
cache_control_notfound_max_age: 900
cache_control_notfound_staleerror: 900
cache_control_notfound_stalereval: 900
cache_control_notfound_s_maxage: 450
cache_control_pages_max_age: 3600
cache_control_pages_staleerror: 7200
cache_control_pages_stalereval: 7200
cache_control_pages_s_maxage: 1800
cache_control_redirect_permanent_max_age: 86400
cache_control_redirect_permanent_staleerror: 86400
cache_control_redirect_permanent_stalereval: 86400
cache_control_redirect_permanent_s_maxage: 43200
cache_control_search_max_age: 1800
cache_control_search_staleerror: 1800
cache_control_search_stalereval: 1800
cache_control_search_s_maxage: 900
cache_control_singles_max_age: 600
cache_control_singles_mmulti: 1
cache_control_singles_staleerror: 600
cache_control_singles_stalereval: 600
cache_control_singles_s_maxage: 300
cache_control_tags_max_age: 900
cache_control_tags_paged: 10
cache_control_tags_staleerror: 900
cache_control_tags_stalereval: 900
cache_control_tags_s_maxage: 450
.label: Cache Control Settings